### ISSUE TITLE
Repeatedly tapping the hamburger menu zooms the camera out infinitely

### ISSUE THREAD

**Issue by ekinney-lang** [kirtonBCIlab/boccia-bci#77] opened 2024-11-20 18:40 UTC
When the hamburger menu is selected multiple times in a row, it continuously adjusts the camera position by a set amount, which can be done infinitely.

**Comment by tm-nielsen** [comment] 2024-11-20 20:15
Potential duplicate of [this issue](https://github.com/kirtonBCIlab/boccia-bci/issues/70).

**Closed as completed** 2024-12-16 22:45 UTC
Labels: bug
